# TRAINING

In [16]:
import cv2
import os
import tensorflow as tf
from tensorflow import keras
from PIL import Image
import numpy as np
import keras
from keras.utils import normalize
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D,Activation,Dropout,Flatten,Dense
from keras.utils import to_categorical

#for splitting the data as train and testing data
from sklearn.model_selection import train_test_split
#80% training and 20% testing

image_directory = 'dataset/'
no_tumor_images=os.listdir(image_directory+ 'no/')
yes_tumor_images=os.listdir(image_directory+ 'yes/')

dataset=[]
label=[]

INPUT_SIZE=34

for i, image_name in enumerate(no_tumor_images):
    if(image_name.split('.')[1]=='jpg'):
        image = cv2.imread(image_directory+ 'no/'+image_name)
        image= Image.fromarray(image,'RGB')
        image=image.resize((INPUT_SIZE,INPUT_SIZE))
        dataset.append(np.array(image))
        label.append(0)
        
for i, image_name in enumerate(yes_tumor_images):
    if(image_name.split('.')[1]=='jpg'):
        image = cv2.imread(image_directory+ 'yes/'+image_name)
        image= Image.fromarray(image,'RGB')
        image=image.resize((INPUT_SIZE,INPUT_SIZE))
        dataset.append(np.array(image))
        label.append(1)
                           
dataset=np.array(dataset)
label=np.array(label)


x_train,x_test,y_train,y_test=train_test_split(dataset,label,test_size=0.2,random_state=0)

#Reshape=(n,image_width,image_height,n_channel)
print(x_train.shape) 
print(y_train.shape)

print(x_test.shape) 
print(y_test.shape)


(2400, 34, 34, 3)
(2400,)
(600, 34, 34, 3)
(600,)


In [8]:
x_train=normalize(x_train,axis=1)
x_test=normalize(x_test,axis=1)

In [17]:
#ModelBuilding
#64,64,3
model=Sequential()
model.add(Conv2D(32,(3,3),input_shape=(INPUT_SIZE,INPUT_SIZE,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32,(3,3),kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32,(3,3),kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

#flatten-allimagesinonefactor
model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))#minimizethefitting
model.add(Dense(1))
model.add(Activation('sigmoid'))

#Binary Cross Entropy=1,sigmoid

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,batch_size=16,verbose=1,epochs=10,
         validation_data=(x_test,y_test),shuffle=False)

model.save('BrainTumor10Epochs.h5')

Epoch 1/10
150/150 [==============================] - 5s 25ms/step - loss: 3.0855 - accuracy: 0.5917 - val_loss: 0.5368 - val_accuracy: 0.7333
Epoch 2/10
150/150 [==============================] - 3s 23ms/step - loss: 0.6452 - accuracy: 0.6629 - val_loss: 0.5549 - val_accuracy: 0.7000
Epoch 3/10
150/150 [==============================] - 3s 23ms/step - loss: 0.6097 - accuracy: 0.6842 - val_loss: 0.5134 - val_accuracy: 0.7217
Epoch 4/10
150/150 [==============================] - 3s 22ms/step - loss: 0.5535 - accuracy: 0.7292 - val_loss: 0.4992 - val_accuracy: 0.7567
Epoch 5/10
150/150 [==============================] - 3s 23ms/step - loss: 0.5045 - accuracy: 0.7608 - val_loss: 0.5345 - val_accuracy: 0.7283
Epoch 6/10
150/150 [==============================] - 4s 23ms/step - loss: 0.4891 - accuracy: 0.7675 - val_loss: 0.3837 - val_accuracy: 0.8183
Epoch 7/10
150/150 [==============================] - 4s 24ms/step - loss: 0.4397 - accuracy: 0.8037 - val_loss: 0.3565 - val_accuracy: 0.8233

In [19]:
y_train=to_categorical(y_train,num_classes=2)
y_test=to_categorical(y_test,num_classes=2)

In [20]:
#ModelBuilding
#64,64,3
model=Sequential()
model.add(Conv2D(32,(3,3),input_shape=(INPUT_SIZE,INPUT_SIZE,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32,(3,3),kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(32,(3,3),kernel_initializer='he_uniform'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

#flatten-allimagesinonefactor
model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))#minimizethefitting
model.add(Dense(2))
model.add(Activation('softmax'))

#Categorical Cross Entropy=2,softmax

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x_train,y_train,batch_size=16,verbose=1,epochs=10,
         validation_data=(x_test,y_test),shuffle=False)

model.save('BrainTumor10EpochsCategorical.h5')

Epoch 1/10
150/150 [==============================] - 5s 26ms/step - loss: 2.5335 - accuracy: 0.6196 - val_loss: 0.5120 - val_accuracy: 0.7517
Epoch 2/10
150/150 [==============================] - 4s 26ms/step - loss: 0.5446 - accuracy: 0.7342 - val_loss: 0.4744 - val_accuracy: 0.7617
Epoch 3/10
150/150 [==============================] - 3s 22ms/step - loss: 0.4820 - accuracy: 0.7775 - val_loss: 0.4687 - val_accuracy: 0.7533
Epoch 4/10
150/150 [==============================] - 4s 25ms/step - loss: 0.4571 - accuracy: 0.7904 - val_loss: 0.4272 - val_accuracy: 0.7750
Epoch 5/10
150/150 [==============================] - 3s 23ms/step - loss: 0.4366 - accuracy: 0.8204 - val_loss: 0.3372 - val_accuracy: 0.8267
Epoch 6/10
150/150 [==============================] - 3s 22ms/step - loss: 0.3711 - accuracy: 0.8338 - val_loss: 0.4427 - val_accuracy: 0.7950
Epoch 7/10
150/150 [==============================] - 3s 22ms/step - loss: 0.3336 - accuracy: 0.8471 - val_loss: 0.3491 - val_accuracy: 0.8517

# TESTING

In [24]:
import cv2
from keras.models import load_model
from PIL import Image
import numpy as np


model=load_model('BrainTumor10Epochs.h5')

In [25]:
image=cv2.imread('C:\\Users\\HZT\\Desktop\\Tumor detection\\pred\\pred0.jpg')

In [38]:
#converting an image to an array
img=Image.fromarray(image)

img=img.resize((34,34))

img=np.array(img)

print(img) #all zeros mean that the image is not affected by the tumor

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [5 5 5]]

 [[0 0 0]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [0 0 0]
  [6 6 6]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [0 0 0]
  [6 6 6]]

 ...

 [[1 1 1]
  [2 2 2]
  [1 1 1]
  ...
  [0 0 0]
  [0 0 0]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [1 1 1]]]


In [39]:
image=cv2.imread('C:\\Users\\HZT\\Desktop\\Tumor detection\\pred\\pred5.jpg')

In [43]:
#converting an image to an array
img=Image.fromarray(image)

img=img.resize((34,34))

img=np.array(img)

print(img) 

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [5 5 5]]

 [[0 0 0]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [0 0 0]
  [6 6 6]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ...
  [1 1 1]
  [0 0 0]
  [6 6 6]]

 ...

 [[1 1 1]
  [2 2 2]
  [1 1 1]
  ...
  [0 0 0]
  [0 0 0]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [1 1 1]]]


In [44]:
img=np.array(img)

input_img=np.expand_dims(img,axis=0)

In [46]:
result=model.predict(input_img)
print(result)

1/1 [==============================] - 0s 30ms/step
[[0.9986723]]


# WEB_APP

In [47]:
import os
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing import image
from PIL import Image
import cv2
from keras.models import load_model
from flask import Flask, request, render_template
from werkzeug.utils import secure_filename


app = Flask(__name__)


model =load_model('BrainTumor10Epochs.h5')
print('Model loaded. Check http://127.0.0.1:5000/')


def get_className(classNo):
	if classNo==0:
		return "No Brain Tumor"
	elif classNo==1:
		return "Yes Brain Tumor"


def getResult(img):
    image=cv2.imread(img)
    image = Image.fromarray(image, 'RGB')
    image = image.resize((64, 64))
    image=np.array(image)
    input_img = np.expand_dims(image, axis=0)
    result=model.predict_classes(input_img)
    return result


@app.route('/', methods=['GET'])
def index():
    return render_template('index.html')


@app.route('/predict', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        f = request.files['file']

        basepath = os.path.dirname(__file__)
        file_path = os.path.join(
            basepath, 'uploads', secure_filename(f.filename))
        f.save(file_path)
        value=getResult(file_path)
        result=get_className(value) 
        return result
    return None


if __name__ == '__main__':
    app.run(debug=True)

Model loaded. Check http://127.0.0.1:5000/
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: on


 * Restarting with watchdog (windowsapi)


SystemExit: 1

C:\Users\HZT\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3377: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [48]:
%tb

SystemExit: 1